

from asclepius.instelling import GGZ

ggmd = GGZ('ggmd')
altrecht = GGZ('ggzaltrecht')
amc = GGZ('ggzamc')
arkin = GGZ('ggzarkin')
azm = GGZ('ggzazm')
breburg = GGZ('ggzbreburg')
centraal = GGZ('ggzcentraal')
delf = GGZ('ggzdelfland')
drenthe = GGZ('ggzdrenthe')
dvs = GGZ('ggzdvs')
eleos = GGZ('ggzeleos')
emc = GGZ('ggzemc')
emergis = GGZ('ggzemergis')
fier = GGZ('ggzfier')
fivoor = GGZ('ggzfivoor')
friesland = GGZ('ggzfriesland')
imp = GGZ('ggzimp')
ingeest = GGZ('ggzingeest')
lentis = GGZ('ggzlentis')
mediant = GGZ('ggzmediant')
met = GGZ('ggzmet')
mondriaan = GGZ('ggzmondriaan')
orbis = GGZ('ggzorbis')
parnassia = GGZ('ggzparnassia')
pp = GGZ('ggzpp')
ps = GGZ('ggzps')
riv = GGZ('ggzriv')
tactus = GGZ('ggztactus')
vvgi = GGZ('ggzvvgi')
waag = GGZ('ggzwaag')
wnb = GGZ('ggzwnb')
nov = GGZ('ggznov')
vnn = GGZ('ggzvnn')
net = GGZ('ggzggnet')
obr = GGZ('ggzobr')
trajectum = GGZ('ggztrajectum')
ihub = GGZ('ihub')

alle_instellingen = [ggmd, altrecht, amc, arkin, azm, breburg, centraal, delf, drenthe, dvs, eleos, emc, emergis, fier, fivoor, friesland, imp, ingeest,
                    lentis, mediant, met, mondriaan, orbis, parnassia, pp, ps, riv, tactus, vvgi, waag, wnb, nov, vnn, net, obr, trajectum, ihub]